"""add_jira_issue_key_to_tasks

Revision ID: 30b0249f866f
Revises: 702231848513
Create Date: 2026-07-11 06:12:59.657552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b0249f866f'
down_revision: Union[str, Sequence[str], None] = '702231848513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implementation_tasks', sa.Column('jira_issue_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('implementation_tasks', 'jira_issue_key')
    # ### end Alembic commands ###
