"""refactor_remediation_draft

Revision ID: 702231848513
Revises: b9b388a12726
Create Date: 2026-07-10 19:47:36.513986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702231848513'
down_revision: Union[str, Sequence[str], None] = 'b9b388a12726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediation_drafts', sa.Column('sop_id', sa.Uuid(), nullable=False))
    op.add_column('remediation_drafts', sa.Column('current_content', sa.Text(), nullable=False))
    op.add_column('remediation_drafts', sa.Column('proposed_revision', sa.Text(), nullable=False))
    op.add_column('remediation_drafts', sa.Column('comments', sa.Text(), nullable=True))
    op.add_column('remediation_drafts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('remediation_drafts_document_id_fkey'), 'remediation_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'remediation_drafts', 'documents', ['sop_id'], ['id'], ondelete='CASCADE')
    op.drop_column('remediation_drafts', 'original_text')
    op.drop_column('remediation_drafts', 'document_id')
    op.drop_column('remediation_drafts', 'proposed_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediation_drafts', sa.Column('proposed_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('remediation_drafts', sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('remediation_drafts', sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'remediation_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('remediation_drafts_document_id_fkey'), 'remediation_drafts', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_column('remediation_drafts', 'updated_at')
    op.drop_column('remediation_drafts', 'comments')
    op.drop_column('remediation_drafts', 'proposed_revision')
    op.drop_column('remediation_drafts', 'current_content')
    op.drop_column('remediation_drafts', 'sop_id')
    # ### end Alembic commands ###
