"""add_requires_tasks_to_remediation_draft

Revision ID: 7e3fb3b95051
Revises: ac47cb028901
Create Date: 2026-07-09 17:04:34.039482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3fb3b95051'
down_revision: Union[str, Sequence[str], None] = 'ac47cb028901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediation_drafts', sa.Column('requires_tasks', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediation_drafts', 'requires_tasks')
    # ### end Alembic commands ###
