"""add_remediation_draft_explanation

Revision ID: ac47cb028901
Revises: 98a6323d1bef
Create Date: 2026-07-09 17:02:25.973011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac47cb028901'
down_revision: Union[str, Sequence[str], None] = '98a6323d1bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediation_drafts', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('remediation_drafts', 'explanation')
    # ### end Alembic commands ###
