"""add_source_to_regulation_update

Revision ID: b9b388a12726
Revises: e7b99c0e4451
Create Date: 2026-07-10 17:50:36.702022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b388a12726'
down_revision: Union[str, Sequence[str], None] = 'e7b99c0e4451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation_updates', sa.Column('source', sa.String(length=50), nullable=True))
    op.execute("UPDATE regulation_updates SET source = 'FDA_API'")
    op.alter_column('regulation_updates', 'source', nullable=False)
    op.add_column('regulation_updates', sa.Column('document_number', sa.String(length=256), nullable=True))
    op.add_column('regulation_updates', sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('regulation_updates', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('regulation_updates', sa.Column('regulatory_authority', sa.String(length=256), nullable=True))
    op.add_column('regulation_updates', sa.Column('category', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regulation_updates', 'category')
    op.drop_column('regulation_updates', 'regulatory_authority')
    op.drop_column('regulation_updates', 'summary')
    op.drop_column('regulation_updates', 'effective_date')
    op.drop_column('regulation_updates', 'document_number')
    op.drop_column('regulation_updates', 'source')
    # ### end Alembic commands ###
