import os
import sys
import uuid
import hashlib
import logging
from datetime import datetime, timezone

# Ensure backend path is available for imports
current_dir = os.path.dirname(os.path.abspath(__file__))
if os.path.exists("/app"):
    sys.path.insert(0, "/app")
else:
    sys.path.insert(0, os.path.abspath(os.path.join(current_dir, "../../backend")))

from sqlalchemy.orm import Session
from app.core.dependencies import engine, SessionLocal
from app.db.base import Base
from app.models.organization import Organization
from app.models.user import User
from app.models.document import Document
from app.models.document_version import DocumentVersion
from app.models.regulation_update import RegulationUpdate
from app.models.impact_assessment import ImpactAssessment
from app.models.remediation_draft import RemediationDraft
from app.models.implementation_task import ImplementationTask
from app.models.approval_record import ApprovalRecord


from app.services.embeddings.embedding_service import embedding_service
from app.services.vector_db.qdrant_client import vector_db_client

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("arex.seed")

# High-Fidelity Mock SOP Contents
SOP_101_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-101
TITLE: ELECTRONIC RECORDS AND SYSTEM ACCESS CONTROL
VERSION: 1

1.0 PURPOSE
This procedure establishes the administrative, technical, and physical controls to ensure system security, access control, and electronic record integrity under FDA 21 CFR Part 11.

2.0 SCOPE
This SOP applies to all computer systems, network domains, and software tools that generate, maintain, modify, retrieve, or transmit quality records.

3.0 SYSTEM ACCESS CONTROLS
3.1 Password Complexity: User passwords must be a minimum of 8 characters, containing at least one uppercase letter, one lowercase letter, one numeric digit, and one special character.
3.2 Session Timeout: Computer terminals and software applications must automatically log out a user or lock the display terminal after 30 minutes of continuous keyboard or mouse inactivity.
3.3 Account Lockout: If a user enters an incorrect password three (3) consecutive times, the system will automatically lock the user account for 30 minutes. Account unlock requests must be approved by the IT System Administrator.
3.4 User Privileges: All write, modification, and approval privileges are strictly restricted according to user roles. Authority checks must be performed before any transaction is executed.
"""

SOP_102_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-102
TITLE: ELECTRONIC SIGNATURES AND SIGNING AUTHORITY
VERSION: 1

1.0 PURPOSE
This procedure governs the definition, application, and verification of electronic signatures to ensure they are the legally binding equivalent of traditional handwritten signatures.

2.0 SCOPE
Applies to all electronic signatures executed on standard operating procedures, validation plans, clinical reports, and batch release records.

3.0 ELECTRONIC SIGNATURE REQUIREMENTS
3.1 Dual-Factor Signature: The execution of an electronic signature requires the input of two distinct identification components: a unique user ID and password, or a biometric identifier combined with password authentication.
3.2 Signature Manifestation: Every electronically signed document must visually display the following three signature components:
  - The printed name of the signer.
  - The date and time stamp (including time zone) when the signature was executed.
  - The meaning associated with the signature (e.g., review, approval, authorship, or responsibility).
3.3 Non-Repudiation: Electronic signatures shall be unique to one individual and shall not be copied, reassigned, or transferred. No two individuals shall share signing credentials.
"""

SOP_103_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-103
TITLE: SYSTEM AUDIT TRAILS AND DATA INTEGRITY
VERSION: 1

1.0 PURPOSE
Defines the management, protection, and review of system audit trails to prevent unauthorized modifications and ensure record traceability.

2.0 SCOPE
Applies to all computer-generated, time-stamped audit trails recording the date, time, user identity, and specific actions of system transactions.

3.0 AUDIT TRAIL MANAGEMENT
3.1 Automatic Generation: Audit trails must be automatically generated by the system and capture all record creation, modification, and deletion events.
3.2 Immutability: Audit trails must be secured against modifications, edits, or deletion by any user, including system administrators and database developers.
3.3 Regular Review: System audit trails must be reviewed by the Quality Assurance (QA) Department at least once every 30 days. Evidence of audit trail review must be documented.
3.4 Retention: Audit trails must be retained for a duration no less than the retention requirements of the electronic records they document.
"""

SOP_104_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-104
TITLE: DOCUMENT LIFECYCLE MANAGEMENT CONTROL
VERSION: 1

1.0 PURPOSE
Governs the creation, review, approval, revision, distribution, and archival of quality system documents.

2.0 SCOPE
Applies to all standard operating procedures, design histories, and manufacturing records.

3.0 DOCUMENT LIFE-CYCLE STATES
3.1 Lifecycle States: All documents must transit through the following defined states:
  - Draft: Under active development.
  - Under Review: Circulating for stakeholder feedback.
  - Approved: Formally signed off and currently in effect.
  - Retired: Replaced by a newer version or decommissioned.
3.2 Superseding: When a document is revised, the new version supersedes the old version. The older version must be immediately flagged as 'Retired' and moved to the archive directory.
3.3 File Archival: Archived files must be stored in read-only folders with modification rights disabled to prevent deletion or overwriting.
"""

SOP_105_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-105
TITLE: CORRECTIVE AND PREVENTIVE ACTION (CAPA) WORKFLOW
VERSION: 1

1.0 PURPOSE
This procedure defines the requirements for establishing, documenting, and executing the Corrective and Preventive Action (CAPA) program to eliminate causes of actual or potential nonconformities.

2.0 SCOPE
Applies to all systemic deviations, out-of-specification results, audit findings, customer complaints, and manufacturing failures requiring formal investigation.

3.0 CAPA PROCEDURE AND PROCESS
3.1 Investigation: A formal investigation must be initiated within five (5) business days of identifying a systemic issue. Root cause analysis must be conducted using structured tools such as the "5 Whys" or Ishikawa diagrams.
3.2 CAPA Plan Design: A detailed CAPA plan must be created, listing corrective actions to resolve the immediate issue and preventive actions to prevent recurrence. Each action must have an assigned owner and target completion date.
3.3 Review and Pre-Approval: The CAPA plan must be reviewed and pre-approved by the QA Manager before implementation.
3.4 Effectiveness Check: All CAPAs must undergo an effectiveness verification review between thirty (30) and ninety (90) days after implementation. The CAPA is considered closed only when QA confirms the actions have effectively prevented recurrence.
"""

SOP_106_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-106
TITLE: CHANGE CONTROL MANAGEMENT PROTOCOL
VERSION: 1

1.0 PURPOSE
This SOP establishes the quality system guidelines to ensure that changes to facilities, equipment, utilities, processes, and validated computer systems are properly evaluated, approved, and documented prior to implementation.

2.0 SCOPE
Applies to any change that has the potential to impact product quality, safety, identity, strength, purity, or the validated state of manufacturing computer systems.

3.0 CHANGE CONTROL CLASSIFICATION AND FLOW
3.1 Classification: Change requests must be classified based on risk:
  - Major Change: High risk, potentially affecting safety, purity, or efficacy. Requires full validation and regulatory pre-approval.
  - Minor Change: Low risk, minimal impact on system performance or product quality. Requires documentation and QA approval.
  - Critical/Emergency Change: Immediate action required to prevent loss of product or safety hazard. Requires verbal authorization followed by formal CC submission within 24 hours.
3.2 Pre-Approval: No change (except emergency actions) may be executed without prior signature approval from the Change Control Board (CCB) and QA Manager.
3.3 Implementation and Testing: Changes must be executed in accordance with the approved plan. Post-change validation testing must be performed to confirm system integrity.
3.4 Final QA Closure: QA must review all post-change testing data, confirm training requirements are met, and formally close the change control request.
"""

SOP_107_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-107
TITLE: COMPUTER SYSTEM VALIDATION (CSV) LIFECYCLE
VERSION: 1

1.0 PURPOSE
Establishes the validation framework for computer systems, databases, and automated equipment to guarantee data integrity, traceability, and compliance with 21 CFR Part 11 and GxP standards.

2.0 SCOPE
Applies to all computerized systems used in GxP operations, including laboratory information systems, manufacturing execution systems, and data archiving servers.

3.0 VALIDATION LIFECYCLE STEPS
3.1 GAMP 5 Classification: All systems must be classified under GAMP 5 categories to determine the validation strategy.
3.2 Validation Planning: A validation plan (VP) must be authored to define the testing strategy, acceptance criteria, and roles.
3.3 Specifications: User Requirement Specifications (URS) and Functional Specifications (FS) must be documented and approved.
3.4 Execution (IQ/OQ/PQ):
  - Installation Qualification (IQ): Verifies hardware and software installation matches specification.
  - Operational Qualification (OQ): Verifies system functions and boundary limits operate as intended.
  - Performance Qualification (PQ): Verifies system consistently performs under routine operational workloads.
3.5 Validation Summary Report (VSR): QA must review and sign the VSR before releasing the computer system for GxP production use.
"""

SOP_108_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-108
TITLE: CLEANROOM ENVIRONMENTAL MONITORING
VERSION: 1

1.0 PURPOSE
This procedure defines the requirements for microbiological and particulate environmental monitoring of aseptic manufacturing facilities to ensure compliance with sterile production standards.

2.0 SCOPE
Applies to all cleanrooms, critical laminar flow hoods, airlocks, and personnel gowning areas associated with sterile pharmaceutical manufacturing.

3.0 MONITORING FREQUENCIES AND LIMITS
3.1 Non-Viable Particulate Limits: Air particle counts must be monitored during operational and static states. ISO Class 5 areas must maintain particle counts of ≤ 3,520 particles/m³ for particles ≥ 0.5 µm.
3.2 Viable Microbial Monitoring: Active air sampling, settle plates (agar exposure), and contact swab plates must be used to monitor microbial contamination.
3.3 Action and Alert Limits: Action limits (prompting formal investigation) and alert limits (triggering increased monitoring) must be established based on historical baseline performance.
3.4 Gowning Certification: Gowning technicians must undergo sterile gowning certification and periodic visual/swab check monitoring to verify compliance with aseptic techniques.
"""

SOP_109_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-109
TITLE: EQUIPMENT CALIBRATION AND PREVENTIVE MAINTENANCE
VERSION: 1

1.0 PURPOSE
Defines the management, scheduling, execution, and documentation of calibration and preventive maintenance for critical laboratory and manufacturing instruments.

2.0 SCOPE
Applies to all GxP scales, temperature sensors, pressure gauges, and analytical instruments.

3.0 CALIBRATION CONTROLS
3.1 Calibration Schedule: Critical instruments must be calibrated according to a defined frequency (e.g., monthly, semi-annually, or annually) using standard operating guidelines.
3.2 Traceability: All calibration standards must be traceable to the National Institute of Standards and Technology (NIST) or international equivalent standards.
3.3 Out-of-Calibration (OOC): If an instrument is found outside its acceptable tolerance range, it must be tagged "Out of Service," and an Out-of-Calibration investigation must be launched immediately to evaluate the impact on previous manufacturing batches.
3.4 Preventive Maintenance (PM): PM procedures must be executed to replace wear-and-tear components (such as gaskets, filters, and O-rings) according to the manufacturer's recommendations.
"""

SOP_110_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-110
TITLE: BATCH RECORD REVIEW AND QUALITY RELEASE
VERSION: 1

1.0 PURPOSE
Governs the systematic review of Batch Manufacturing Records (BMR) and analytical testing records to ensure batches conform to specifications before final release to market.

2.0 SCOPE
Applies to all commercial batches of drug substances and drug products manufactured by BioPharma Corp.

3.0 RELEASE PROCESS
3.1 Batch Record Audit: The manufacturing supervisor must review the completed BMR, verifying that all entries are complete, calculations are correct, and signatures are in place.
3.2 Deviation Review: All deviations, failures, and OOS investigations associated with the batch must be resolved and closed by QA before final batch release.
3.3 QA Certificate of Analysis (CoA): Analytical test results must match standard release specifications. A CoA must be compiled and signed off by the Quality Control lab.
3.4 Electronic Signature Release: The QA Manager executes the final release decision using a dual-factor electronic signature, confirming the batch was manufactured in strict compliance with GMP guidelines.
"""


def get_password_hash(password: str) -> str:
    return hashlib.sha256(password.encode()).hexdigest()


def chunk_text(text: str, chunk_size: int = 400, overlap: int = 100) -> list[str]:
    # A simple word-level chunker for seed scripting
    words = text.split()
    chunks = []
    i = 0
    while i < len(words):
        chunk_words = words[i:i + chunk_size]
        chunks.append(" ".join(chunk_words))
        if i + chunk_size >= len(words):
            break
        i += (chunk_size - overlap)
    return chunks


def seed_database():
    # 1. Initialize Qdrant collection
    logger.info("Initializing Qdrant vector index...")
    vector_db_client.init_collection()

    db: Session = SessionLocal()
    try:
        logger.info("Clearing existing database tables...")
        # Order of deletion is important to satisfy foreign keys
        db.query(ApprovalRecord).delete()
        db.query(ImplementationTask).delete()
        db.query(RemediationDraft).delete()
        db.query(ImpactAssessment).delete()
        db.query(DocumentVersion).delete()
        db.query(Document).delete()
        db.query(User).delete()
        db.query(RegulationUpdate).delete()
        db.query(Organization).delete()
        db.commit()

        # 2. Seed Organization
        org_id = uuid.UUID("9280d0d8-5527-4632-bd92-4fcf05c75462")
        org = Organization(
            id=org_id,
            name="BioPharma Corp",
            created_at=datetime.now(timezone.utc)
        )
        db.add(org)
        db.commit()
        logger.info("Seeded Organization: BioPharma Corp")

        # 3. Seed Users
        user_qa = User(
            id=uuid.UUID("40bb96dc-6e9f-431f-b5de-84d7a188f58b"),
            email="qa@biopharma.com",
            hashed_password=get_password_hash("password"),
            role="QA Manager",
            organization_id=org_id,
            created_at=datetime.now(timezone.utc)
        )
        user_eng = User(
            id=uuid.UUID("759f21f7-e7d6-444a-a92c-56961421ab7b"),
            email="eng@biopharma.com",
            hashed_password=get_password_hash("password"),
            role="Validation Engineer",
            organization_id=org_id,
            created_at=datetime.now(timezone.utc)
        )
        db.add(user_qa)
        db.add(user_eng)
        db.commit()
        logger.info("Seeded users: qa@biopharma.com, eng@biopharma.com")

        # Create raw storage folder in the container
        storage_dir = "/app/storage"
        os.makedirs(storage_dir, exist_ok=True)

        # 4. Seed Documents & Vector DB chunks
        sops = [
            ("SOP-101.txt", SOP_101_TEXT, "SOP-101: Access Control"),
            ("SOP-102.txt", SOP_102_TEXT, "SOP-102: Electronic Signatures"),
            ("SOP-103.txt", SOP_103_TEXT, "SOP-103: Audit Trails"),
            ("SOP-104.txt", SOP_104_TEXT, "SOP-104: Document Lifecycle"),
            ("SOP-105.txt", SOP_105_TEXT, "SOP-105: CAPA Program"),
            ("SOP-106.txt", SOP_106_TEXT, "SOP-106: Change Control"),
            ("SOP-107.txt", SOP_107_TEXT, "SOP-107: CSV Lifecycle"),
            ("SOP-108.txt", SOP_108_TEXT, "SOP-108: Cleanroom Environmental Monitoring"),
            ("SOP-109.txt", SOP_109_TEXT, "SOP-109: Equipment Calibration"),
            ("SOP-110.txt", SOP_110_TEXT, "SOP-110: Batch Record Review and Release")
        ]

        doc_models = []
        for filename, text, desc in sops:
            doc_id = uuid.uuid4()
            file_path = os.path.join(storage_dir, f"{doc_id}.txt")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(text)

            doc = Document(
                id=doc_id,
                organization_id=org_id,
                filename=filename,
                file_path=file_path,
                parsed_text=text,
                version=1,
                created_at=datetime.now(timezone.utc)
            )
            db.add(doc)
            doc_models.append(doc)
            db.flush()  # populate ID

            # Create document version history entry
            db_version = DocumentVersion(
                id=uuid.uuid4(),
                document_id=doc.id,
                version=1,
                filename=filename,
                file_path=file_path,
                parsed_text=text,
                reason_for_revision="Initial upload",
                created_at=doc.created_at
            )
            db.add(db_version)

            # Chunk text and embed
            logger.info(f"Chunking and embedding {filename}...")
            text_chunks = chunk_text(text, chunk_size=150, overlap=30)
            vectors = embedding_service.get_embeddings(text_chunks)
            
            qdrant_chunks = []
            for idx, (chunk_text_str, vector) in enumerate(zip(text_chunks, vectors)):
                qdrant_chunks.append({
                    "text": chunk_text_str,
                    "vector": vector,
                    "chunk_index": idx
                })
            
            # Index in Qdrant
            vector_db_client.upsert_chunks(doc.id, org_id, qdrant_chunks)

        db.commit()
        logger.info("Seeded documents and indexed in Qdrant successfully.")

        db.commit()
        logger.info("Successfully seeded all database tables with demo GxP data.")
        logger.info("No regulations seeded — click 'Fetch from FDA' in the UI to load real live FDA regulations.")



    except Exception as e:
        db.rollback()
        logger.error(f"Error seeding database: {e}")
        raise e
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
