import os
import sys
import uuid
import hashlib
import logging
from datetime import datetime, timezone

# Ensure backend path is available for imports
current_dir = os.path.dirname(os.path.abspath(__file__))
if os.path.exists("/app"):
    sys.path.insert(0, "/app")
else:
    sys.path.insert(0, os.path.abspath(os.path.join(current_dir, "../../backend")))

from sqlalchemy.orm import Session
from app.core.dependencies import engine, SessionLocal
from app.db.base import Base
from app.models.organization import Organization
from app.models.user import User
from app.models.document import Document
from app.models.document_version import DocumentVersion
from app.models.regulation_update import RegulationUpdate
from app.models.impact_assessment import ImpactAssessment
from app.models.remediation_draft import RemediationDraft
from app.models.implementation_task import ImplementationTask
from app.models.approval_record import ApprovalRecord

from app.services.embeddings.embedding_service import embedding_service
from app.services.vector_db.qdrant_client import vector_db_client

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("arex.seed")

# High-Fidelity Mock SOP Contents
SOP_101_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-101
TITLE: ELECTRONIC RECORDS AND SYSTEM ACCESS CONTROL
VERSION: 1

1.0 PURPOSE
This procedure establishes the administrative, technical, and physical controls to ensure system security, access control, and electronic record integrity under FDA 21 CFR Part 11.

2.0 SCOPE
This SOP applies to all computer systems, network domains, and software tools that generate, maintain, modify, retrieve, or transmit quality records.

3.0 SYSTEM ACCESS CONTROLS
3.1 Password Complexity: User passwords must be a minimum of 8 characters, containing at least one uppercase letter, one lowercase letter, one numeric digit, and one special character.
3.2 Session Timeout: Computer terminals and software applications must automatically log out a user or lock the display terminal after 30 minutes of continuous keyboard or mouse inactivity.
3.3 Account Lockout: If a user enters an incorrect password three (3) consecutive times, the system will automatically lock the user account for 30 minutes. Account unlock requests must be approved by the IT System Administrator.
3.4 User Privileges: All write, modification, and approval privileges are strictly restricted according to user roles. Authority checks must be performed before any transaction is executed.
"""

SOP_102_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-102
TITLE: ELECTRONIC SIGNATURES AND SIGNING AUTHORITY
VERSION: 1

1.0 PURPOSE
This procedure governs the definition, application, and verification of electronic signatures to ensure they are the legally binding equivalent of traditional handwritten signatures.

2.0 SCOPE
Applies to all electronic signatures executed on standard operating procedures, validation plans, clinical reports, and batch release records.

3.0 ELECTRONIC SIGNATURE REQUIREMENTS
3.1 Dual-Factor Signature: The execution of an electronic signature requires the input of two distinct identification components: a unique user ID and password, or a biometric identifier combined with password authentication.
3.2 Signature Manifestation: Every electronically signed document must visually display the following three signature components:
  - The printed name of the signer.
  - The date and time stamp (including time zone) when the signature was executed.
  - The meaning associated with the signature (e.g., review, approval, authorship, or responsibility).
3.3 Non-Repudiation: Electronic signatures shall be unique to one individual and shall not be copied, reassigned, or transferred. No two individuals shall share signing credentials.
"""

SOP_103_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-103
TITLE: SYSTEM AUDIT TRAILS AND DATA INTEGRITY
VERSION: 1

1.0 PURPOSE
Defines the management, protection, and review of system audit trails to prevent unauthorized modifications and ensure record traceability.

2.0 SCOPE
Applies to all computer-generated, time-stamped audit trails recording the date, time, user identity, and specific actions of system transactions.

3.0 AUDIT TRAIL MANAGEMENT
3.1 Automatic Generation: Audit trails must be automatically generated by the system and capture all record creation, modification, and deletion events.
3.2 Immutability: Audit trails must be secured against modifications, edits, or deletion by any user, including system administrators and database developers.
3.3 Regular Review: System audit trails must be reviewed by the Quality Assurance (QA) Department at least once every 30 days. Evidence of audit trail review must be documented.
3.4 Retention: Audit trails must be retained for a duration no less than the retention requirements of the electronic records they document.
"""

SOP_104_TEXT = """
STANDARD OPERATING PROCEDURE: SOP-104
TITLE: DOCUMENT LIFECYCLE MANAGEMENT CONTROL
VERSION: 1

1.0 PURPOSE
Governs the creation, review, approval, revision, distribution, and archival of quality system documents.

2.0 SCOPE
Applies to all standard operating procedures, design histories, and manufacturing records.

3.0 DOCUMENT LIFE-CYCLE STATES
3.1 Lifecycle States: All documents must transit through the following defined states:
  - Draft: Under active development.
  - Under Review: Circulating for stakeholder feedback.
  - Approved: Formally signed off and currently in effect.
  - Retired: Replaced by a newer version or decommissioned.
3.2 Superseding: When a document is revised, the new version supersedes the old version. The older version must be immediately flagged as 'Retired' and moved to the archive directory.
3.3 File Archival: Archived files must be stored in read-only folders with modification rights disabled to prevent deletion or overwriting.
"""


def get_password_hash(password: str) -> str:
    return hashlib.sha256(password.encode()).hexdigest()


def chunk_text(text: str, chunk_size: int = 400, overlap: int = 100) -> list[str]:
    # A simple word-level chunker for seed scripting
    words = text.split()
    chunks = []
    i = 0
    while i < len(words):
        chunk_words = words[i:i + chunk_size]
        chunks.append(" ".join(chunk_words))
        if i + chunk_size >= len(words):
            break
        i += (chunk_size - overlap)
    return chunks


def seed_database():
    # 1. Initialize Qdrant collection
    logger.info("Initializing Qdrant vector index...")
    vector_db_client.init_collection()

    db: Session = SessionLocal()
    try:
        logger.info("Clearing existing database tables...")
        # Order of deletion is important to satisfy foreign keys
        db.query(ApprovalRecord).delete()
        db.query(ImplementationTask).delete()
        db.query(RemediationDraft).delete()
        db.query(ImpactAssessment).delete()
        db.query(DocumentVersion).delete()
        db.query(Document).delete()
        db.query(User).delete()
        db.query(RegulationUpdate).delete()
        db.query(Organization).delete()
        db.commit()

        # 2. Seed Organization
        org_id = uuid.UUID("9280d0d8-5527-4632-bd92-4fcf05c75462")
        org = Organization(
            id=org_id,
            name="BioPharma Corp",
            created_at=datetime.now(timezone.utc)
        )
        db.add(org)
        db.commit()
        logger.info("Seeded Organization: BioPharma Corp")

        # 3. Seed Users
        user_qa = User(
            id=uuid.uuid4(),
            email="qa@biopharma.com",
            hashed_password=get_password_hash("password"),
            role="QA Manager",
            organization_id=org_id,
            created_at=datetime.now(timezone.utc)
        )
        user_eng = User(
            id=uuid.uuid4(),
            email="eng@biopharma.com",
            hashed_password=get_password_hash("password"),
            role="Validation Engineer",
            organization_id=org_id,
            created_at=datetime.now(timezone.utc)
        )
        db.add(user_qa)
        db.add(user_eng)
        db.commit()
        logger.info("Seeded users: qa@biopharma.com, eng@biopharma.com")

        # Create raw storage folder in the container
        storage_dir = "/app/storage"
        os.makedirs(storage_dir, exist_ok=True)

        # 4. Seed Documents & Vector DB chunks
        sops = [
            ("SOP-101.txt", SOP_101_TEXT, "SOP-101: Access Control"),
            ("SOP-102.txt", SOP_102_TEXT, "SOP-102: Electronic Signatures"),
            ("SOP-103.txt", SOP_103_TEXT, "SOP-103: Audit Trails"),
            ("SOP-104.txt", SOP_104_TEXT, "SOP-104: Document Lifecycle")
        ]

        doc_models = []
        for filename, text, desc in sops:
            doc_id = uuid.uuid4()
            file_path = os.path.join(storage_dir, f"{doc_id}.txt")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(text)

            doc = Document(
                id=doc_id,
                organization_id=org_id,
                filename=filename,
                file_path=file_path,
                parsed_text=text,
                version=1,
                created_at=datetime.now(timezone.utc)
            )
            db.add(doc)
            doc_models.append(doc)
            db.flush()  # populate ID

            # Create document version history entry
            db_version = DocumentVersion(
                id=uuid.uuid4(),
                document_id=doc.id,
                version=1,
                filename=filename,
                file_path=file_path,
                parsed_text=text,
                reason_for_revision="Initial upload",
                created_at=doc.created_at
            )
            db.add(db_version)

            # Chunk text and embed
            logger.info(f"Chunking and embedding {filename}...")
            text_chunks = chunk_text(text, chunk_size=150, overlap=30)
            vectors = embedding_service.get_embeddings(text_chunks)
            
            qdrant_chunks = []
            for idx, (chunk_text_str, vector) in enumerate(zip(text_chunks, vectors)):
                qdrant_chunks.append({
                    "text": chunk_text_str,
                    "vector": vector,
                    "chunk_index": idx
                })
            
            # Index in Qdrant
            vector_db_client.upsert_chunks(doc.id, org_id, qdrant_chunks)

        db.commit()
        logger.info("Seeded documents and indexed in Qdrant successfully.")

        # 5. Seed a new Regulation Update
        reg_id = uuid.UUID("a0f2c416-24e0-4c12-a72e-07a829e1eb1c")
        reg_text = (
            "The Food and Drug Administration (FDA) is amending its regulations regarding electronic records "
            "and electronic signatures (21 CFR Part 11). This amendment establishes that all electronic systems "
            "used to manage clinical trial data or quality management records must implement mandatory "
            "Multi-Factor Authentication (MFA) for access control. Simple password-only authentication is no "
            "longer considered sufficient. Furthermore, session idle timeouts must be enforced at a maximum limit "
            "of 15 minutes. Failure to comply with these rules by December 31, 2026, will result in warning letters "
            "and possible suspension of product approvals."
        )
        
        reg_hash = hashlib.sha256(reg_text.encode("utf-8")).hexdigest()
        reg_update = RegulationUpdate(
            id=reg_id,
            source_url="https://www.federalregister.gov/documents/2026/07/05/21-cfr-part-11-mfa-rules",
            title="FDA Mandatory Multi-Factor Authentication and Session Idle Timeout Requirements (2026)",
            published_date=datetime(2026, 7, 5, tzinfo=timezone.utc),
            raw_content=reg_text,
            parsed_sections={
                "section_3.1": "Access Control Systems must implement Multi-Factor Authentication (MFA).",
                "section_3.2": "Session idle timeouts must not exceed 15 minutes of inactivity."
            },
            hash_value=reg_hash,
            status="classified",
            created_at=datetime.now(timezone.utc)
        )
        db.add(reg_update)
        db.commit()
        logger.info("Seeded regulation: Part 11 MFA & Session Timeout Amendment")

        # Find the SOP-101 document model to map remediation draft
        sop_101_model = [d for d in doc_models if d.filename == "SOP-101.txt"][0]

        # 6. Seed Impact Assessment
        impact = ImpactAssessment(
            id=uuid.uuid4(),
            regulation_id=reg_id,
            organization_id=org_id,
            risk_score=0.85,
            impact_level="High",
            rationale=(
                "The new FDA amendment mandates Multi-Factor Authentication (MFA) and reduces the permissible idle "
                "timeout limit to 15 minutes. Our current SOP-101 (Access Control) does not require MFA and permits "
                "a 30-minute idle session timeout. This constitutes a high-priority compliance gap requiring immediate revision."
            ),
            affected_departments=["IT Department", "Quality Assurance"],
            affected_documents=[
                {
                    "document_id": str(sop_101_model.id),
                    "document_name": "SOP-101.txt",
                    "document_type": "SOP",
                    "affected_sections": "3.2 Session Timeout: Computer terminals and software applications must automatically log out a user or lock the display terminal after 30 minutes of continuous keyboard or mouse inactivity.",
                    "explanation": "Our current SOP-101 permits a 30-minute idle session timeout and does not specify MFA controls, creating a direct compliance gap.",
                    "confidence_score": 95.0
                }
            ],
            status="pending",
            created_at=datetime.now(timezone.utc)
        )
        db.add(impact)


        # 7. Seed Remediation Draft
        proposed_remediation_text = SOP_101_TEXT.replace(
            "3.1 Password Complexity: User passwords must be a minimum of 8 characters, containing at least one uppercase letter, one lowercase letter, one numeric digit, and one special character.",
            "3.1 Password Complexity: User passwords must be a minimum of 8 characters, containing at least one uppercase letter, one lowercase letter, one numeric digit, and one special character. Additionally, Multi-Factor Authentication (MFA) must be enforced for all users."
        ).replace(
            "3.2 Session Timeout: Computer terminals and software applications must automatically log out a user or lock the display terminal after 30 minutes of continuous keyboard or mouse inactivity.",
            "3.2 Session Timeout: Computer terminals and software applications must automatically log out a user or lock the display terminal after 15 minutes of continuous keyboard or mouse inactivity."
        )

        remediation = RemediationDraft(
            id=uuid.uuid4(),
            sop_id=sop_101_model.id,
            regulation_id=reg_id,
            proposed_revision=proposed_remediation_text,
            current_content=SOP_101_TEXT,
            diff_content={
                "added": [
                    "Additionally, Multi-Factor Authentication (MFA) must be enforced for all users.",
                    "after 15 minutes of continuous keyboard or mouse inactivity (reduced from 30 minutes)."
                ],
                "removed": [
                    "after 30 minutes of continuous keyboard or mouse inactivity."
                ]
            },
            explanation="Updates password policy to mandate MFA and reduces idle session timeouts to 15 minutes to satisfy Part 11 requirements.",
            status="Under Review",
            reviewer_id=None,
            reviewed_at=None,
            created_at=datetime.now(timezone.utc)
        )
        db.add(remediation)
        db.flush()

        # 8. Seed Implementation Tasks
        task1 = ImplementationTask(
            id=uuid.uuid4(),
            regulation_id=reg_id,
            remediation_draft_id=remediation.id,
            title="Implement Multi-Factor Authentication (MFA) in Active Directory",
            description="Configure active directory integration and mandate MFA enrollment for all users accessing GxP validated servers.",
            department="IT",
            priority="High",
            status="TODO",
            created_at=datetime.now(timezone.utc)
        )
        task2 = ImplementationTask(
            id=uuid.uuid4(),
            regulation_id=reg_id,
            remediation_draft_id=remediation.id,
            title="Configure Session Idle Timeout to 15 Minutes on Validation Systems",
            description="Update system group policies and web-app timeout controls to terminate user login sessions after 15 minutes of inactivity.",
            department="Engineering",
            priority="Medium",
            status="TODO",
            created_at=datetime.now(timezone.utc)
        )
        db.add(task1)
        db.add(task2)
        
        db.commit()
        logger.info("Successfully seeded all database tables with demo GxP data.")

    except Exception as e:
        db.rollback()
        logger.error(f"Error seeding database: {e}")
        raise e
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
